language: csharp
mono: none
dotnet: 2.1.403
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
os:
  - linux
  - osx
osx_image: xcode8.2
branches:
  only:
    - master
    - release
    - dev
    - appveyor
    - /^(.*\/)?ci-.*$/
    - /^rel\/.*/
before_install:
  - chmod ugo+x build.sh
script:
  - ./build.sh
